## <span style="color:grey; font-weight:bold;">Import Tool</span>

In [7]:
import pandas as pd
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Embedding, Dropout, Flatten
from tensorflow.keras.models import Sequential

## <span style="color:grey; font-weight:bold;">Import Data</span>

In [2]:
data_path = '/Users/porter/Desktop/01.Data Science/Porter - Project/05 - Advertising Challenge - Data Analysis/Data'
os.chdir(data_path)

files = os.listdir()
print(files)

['.DS_Store', 'Data Preprocessing Chunk 1.csv', 'train.txt', 'Data Preprocessing Chunk 2.csv', 'Data Preprocessing Chunk 3.csv', 'Data Preprocessing Chunk 4.csv', 'encoder_dict.joblib', 'Data Preprocessing Chunk 5.csv', 'Base Train DataFrame Chunk3.csv', 'Base Train DataFrame Chunk2.csv', 'X_train.csv', 'Base Train DataFrame Chunk1.csv', 'Base Train DataFrame Chunk5.csv', 'Base Train DataFrame Chunk4.csv', 'readme.txt', 'test.txt', 'Y_train.csv', 'Y_test.csv', 'X_test.csv']

In [3]:
x_train = pd.read_csv('X_train.csv', sep=',')
x_test = pd.read_csv('X_test.csv', sep=',')
y_train = pd.read_csv('Y_train.csv', sep=',')
y_test = pd.read_csv('Y_test.csv', sep=',')

## <span style="color:skyblue; font-weight:bold;">Data Preprocessing - Embedding</span>

In [5]:
round(x_train, 2)

,1,3,4,5,6,7,10,11,13,22,27,30,33
0,0.37,0.49,0.31,0.46,0.23,0.00,0.09,0.00,0.33,1.0,0.08,0.56,0.0
1,0.37,0.61,0.54,0.28,0.33,0.63,0.00,0.62,0.58,1.0,0.65,1.00,0.5
2,0.00,0.16,0.31,0.37,0.32,0.36,0.00,0.29,0.29,1.0,0.08,0.00,0.0
3,0.00,0.64,0.62,0.28,0.29,0.62,0.00,0.78,0.58,1.0,0.46,1.00,0.0
4,0.77,0.44,0.14,0.27,0.14,0.42,0.09,0.29,0.37,1.0,0.08,1.00,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16756408,0.52,0.79,0.31,0.06,0.19,0.23,0.09,0.29,0.30,1.0,0.08,1.00,1.0
16756409,0.60,0.16,0.14,0.10,0.04,0.57,0.08,0.50,0.13,1.0,0.69,1.00,1.0
16756410,0.37,0.65,0.41,0.39,0.39,0.23,0.09,0.29,0.39,1.0,0.65,0.00,0.0
16756411,0.85,0.29,0.34,0.00,0.00,0.64,0.09,0.71,0.00,1.0,0.69,1.00,0.0
16756412,0.75,0.70,0.53,0.25,0.25,0.56,0.08,0.50,0.58,1.0,0.69,1.00,0.0

In [8]:
objective_col = ['22', '27', '30', '33']
numerical_col = ['1', '3', '4', '5', '6', '7', '10', '11', '13']

x_train = pd.get_dummies(x_train, columns=objective_col)
x_train.head()

,1,3,4,5,6,7,10,11,13,22_0.0,...,30_0.3333333333333333,30_0.4444444444444444,30_0.5555555555555556,30_0.6666666666666666,30_0.7777777777777777,30_0.8888888888888888,30_1.0,33_0.0,33_0.5,33_1.0
0,0.370029,0.494364,0.309489,0.464066,0.230839,0.000000,0.090909,0.000000,0.325289,False,...,False,False,True,False,False,False,False,True,False,False
1,0.370128,0.609870,0.540390,0.275831,0.329221,0.626601,0.000000,0.623702,0.581369,False,...,False,False,False,False,False,False,True,False,True,False
2,0.000000,0.157311,0.309449,0.371063,0.315088,0.357236,0.000000,0.289858,0.294248,False,...,False,False,False,False,False,False,False,True,False,False
3,0.000000,0.636353,0.617290,0.281372,0.288141,0.620460,0.000000,0.778251,0.576026,False,...,False,False,False,False,False,False,True,True,False,False
4,0.770357,0.436883,0.139614,0.269970,0.141116,0.415898,0.090909,0.288068,0.370117,False,...,False,False,False,False,False,False,True,False,True,False

In [10]:
feature_col = []
for col in x_train.columns:
    feature_col.append(x_train[col])

In [11]:
deepfm_base_model = keras.Sequential(
    keras.layers.DenseFeatures(feature_col.columns),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
)

deepfm_base_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

base_history = deepfm_base_model.fit(x_train, y_train, epochs=10, batch_size=32)

AttributeError: module 'tensorflow.keras.layers' has no attribute 'DenseFeatures'